import { useEffect, useMemo, useState } from 'react'
import { ANALYSTS, DOC_STATUS, STATUS, analystName, createDemoDossiers, dateLabel, money, type Dossier, type DossierStatus } from './demoData'
import { BoIcon, type BoIconName } from './BoIcon'
import { DossierDrawer, type ActionPayload } from './DossierDrawer'
import './backoffice.css'

type Page = 'overview' | 'dossiers' | 'documents' | 'analysts' | 'activity'
const NAV: { id: Page; label: string; icon: BoIconName }[] = [
  { id: 'overview', label: 'Vue d’ensemble', icon: 'grid' }, { id: 'dossiers', label: 'Dossiers', icon: 'folder' },
  { id: 'documents', label: 'Documents', icon: 'file' }, { id: 'analysts', label: 'Analystes', icon: 'users' }, { id: 'activity', label: 'Activité', icon: 'clock' },
]
const TITLES: Record<Page, string> = { overview: 'Une vue claire sur votre activité.', dossiers: 'Dossiers de financement', documents: 'La bibliothèque documentaire', analysts: 'La bonne expertise, au bon dossier.', activity: 'Chaque action laisse une trace.' }
const SUBTITLES: Record<Page, string> = { overview: 'Les dossiers à suivre, les priorités et la charge de votre équipe.', dossiers: 'Consultez, affectez et suivez les demandes de vos clients.', documents: 'CIN, ICE et pièces justificatives, réunies dans un seul espace.', analysts: 'Suivez les affectations et répartissez la charge de traitement.', activity: 'Un journal partagé des traitements et des échanges simulés.' }

export function BackOffice() {
  const [dossiers, setDossiers] = useState(createDemoDossiers)
  const [page, setPage] = useState<Page>('dossiers')
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [selectedDocumentId, setSelectedDocumentId] = useState<string | null>(null)
  const openDossier = (id: string, docId: string | null = null) => { setSelectedDocumentId(docId); setSelectedId(id) }
  const [status, setStatus] = useState<DossierStatus | 'all'>('all')
  const [search, setSearch] = useState('')
  const [analyst, setAnalyst] = useState('all')
  const [priorityOnly, setPriorityOnly] = useState(false)
  const [sort, setSort] = useState('recent')
  const [listPage, setListPage] = useState(1)
  const [docFilter, setDocFilter] = useState('all')
  const [toast, setToast] = useState('')
  const [resetConfirm, setResetConfirm] = useState(false)
  useEffect(() => { const previous = window.document.title; window.document.title = 'Back-office · Wafabail · Démo'; return () => { window.document.title = previous } }, [])
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4500); return () => clearTimeout(timer) }, [toast])
  const selected = dossiers.find(d => d.id === selectedId)
  const counts = Object.fromEntries(Object.keys(STATUS).map(key => [key, dossiers.filter(d => d.status === key).length])) as Record<DossierStatus, number>
  const active = dossiers.filter(d => ['new', 'analysis', 'revision'].includes(d.status))
  const outstanding = dossiers.reduce((sum, d) => sum + d.documents.filter(doc => ['replace', 'missing'].includes(doc.status)).length, 0)
  const navigate = (next: Page) => { setPage(next); setSearch(''); setListPage(1); setResetConfirm(false) }
  const matchesSearch = (d: Dossier) => `${d.company} ${d.id} ${d.contact} ${d.city}`.toLocaleLowerCase().includes(search.toLocaleLowerCase().trim())
  const filtered = useMemo(() => dossiers.filter(d => (status === 'all' || d.status === status) && (analyst === 'all' || (analyst === 'none' ? !d.analyst : d.analyst === analyst)) && (!priorityOnly || d.priority) && `${d.company} ${d.id} ${d.contact} ${d.city}`.toLocaleLowerCase().includes(search.toLocaleLowerCase().trim())).sort((a, b) => sort === 'amount' ? b.amount - a.amount : sort === 'oldest' ? a.date.localeCompare(b.date) : b.date.localeCompare(a.date)), [dossiers, status, analyst, priorityOnly, search, sort])
  const pageCount = Math.max(1, Math.ceil(filtered.length / 6))
  const currentPage = Math.min(listPage, pageCount)
  const visible = filtered.slice((currentPage - 1) * 6, currentPage * 6)
  const documents = dossiers.filter(matchesSearch).flatMap(d => d.documents.map(doc => ({ dossier: d, doc }))).filter(({ doc }) => docFilter === 'all' || doc.status === docFilter || doc.kind.startsWith(docFilter))
  const activity = dossiers.flatMap(d => d.events.map(event => ({ event, dossier: d }))).filter(({ dossier }) => matchesSearch(dossier)).sort((a, b) => b.event.date.localeCompare(a.event.date))

  const performAction = (id: string, payload: ActionPayload) => {
    const dossier = dossiers.find(d => d.id === id)
    if (!dossier) return
    const canEdit = ['new', 'analysis', 'revision'].includes(dossier.status)
    const titles: Record<ActionPayload['type'], string> = { assign: 'Dossier affecté', reject: 'Dossier rejeté', revision: 'Retour client demandé', approve: 'Dossier validé', archive: 'Dossier archivé', restore: 'Dossier rouvert', priority: dossier.priority ? 'Priorité retirée' : 'Dossier marqué prioritaire', note: 'Note interne ajoutée', validate: 'Pièce vérifiée', resubmit: 'Nouvelle version reçue du client' }
    if ((['reject', 'revision', 'priority', 'validate'].includes(payload.type) && !canEdit) || (payload.type === 'assign' && (!['new', 'analysis'].includes(dossier.status) || !ANALYSTS.some(a => a.id === payload.analyst)))) return
    if (['reject', 'revision'].includes(payload.type) && (!payload.message || payload.message.trim().length < 10)) return
    if (payload.type === 'revision' && !payload.simulation && !payload.documents?.length) return
    if (payload.type === 'approve' && (dossier.status !== 'analysis' || !dossier.documents.every(doc => doc.status === 'validated'))) return
    if (payload.type === 'archive' && !['approved', 'rejected'].includes(dossier.status)) return
    if (payload.type === 'restore' && dossier.status !== 'archived') return
    if (payload.type === 'resubmit' && (dossier.status !== 'revision' || !dossier.revision)) return
    const date = new Date().toISOString()
    let detail = payload.message ?? ''
    if (payload.type === 'assign') detail = `Transfert simulé à ${analystName(payload.analyst ?? null)}.`
    if (payload.type === 'revision') detail += ` À refaire : ${[payload.simulation ? 'simulation' : '', ...dossier.documents.filter(doc => payload.documents?.includes(doc.id)).map(doc => doc.kind)].filter(Boolean).join(', ')}.`
    if (payload.type === 'validate') detail = dossier.documents.find(doc => doc.id === payload.documents?.[0])?.kind ?? ''
    if (payload.type === 'approve') detail = 'Validation simulée. Aucun engagement de financement.'
    if (payload.type === 'resubmit') detail = 'Simulation et pièces demandées mises à jour avec des exemples fictifs. Dossier à revérifier.'
    const event = { id: crypto.randomUUID(), date, title: titles[payload.type], detail, actor: payload.type === 'resubmit' ? 'Client · démo' : 'Amine · Gestionnaire démo' }
    setDossiers(previous => previous.map(d => {
      if (d.id !== id) return d
      let next = { ...d, events: [event, ...d.events] }
      switch (payload.type) {
        case 'assign': next = { ...next, analyst: payload.analyst!, status: 'analysis' }; break
        case 'reject': next = { ...next, status: 'rejected', revision: null }; break
        case 'revision': next = { ...next, status: 'revision', revision: { message: payload.message!, simulation: !!payload.simulation, documents: payload.documents ?? [] }, documents: d.documents.map(doc => payload.documents?.includes(doc.id) && doc.status !== 'missing' ? { ...doc, status: 'replace' } : doc) }; break
        case 'approve': next.status = 'approved'; break
        case 'archive': next.status = 'archived'; break
        case 'restore': next = { ...next, status: 'new', analyst: null, revision: null }; break
        case 'priority': next.priority = !d.priority; break
        case 'note': next.notes = [event, ...d.notes]; break
        case 'validate': next.documents = d.documents.map(doc => payload.documents?.includes(doc.id) && doc.status === 'review' ? { ...doc, status: 'validated' } : doc); break
        case 'resubmit': next = { ...next, status: d.analyst ? 'analysis' : 'new', amount: payload.amount ?? d.amount, revision: null, documents: d.documents.map(doc => d.revision?.documents.includes(doc.id) ? { ...doc, status: 'review', name: doc.name.replace('_DEMO.svg', '_v2_DEMO.svg') } : doc) }; break
      }
      return next
    }))
    setToast(`${titles[payload.type]} · simulation locale`)
  }
  const exportCsv = () => {
    const selection = page === 'overview' ? dossiers : filtered
    const rows = [['Référence', 'Client fictif', 'Contact', 'Ville', 'Montant DH', 'Statut', 'Analyste'], ...selection.map(d => [d.id, d.company, d.contact, d.city, String(d.amount), STATUS[d.status].label, analystName(d.analyst)])]
    const csv = '\uFEFF' + rows.map(row => row.map(cell => `"${cell.replaceAll('"', '""')}"`).join(';')).join('\r\n')
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); const link = window.document.createElement('a'); link.href = url; link.download = 'wafabail-dossiers-DEMO.csv'; window.document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 10000)
    setToast(`Export préparé · ${selection.length} dossiers fictifs`)
  }
  const clearFilters = () => { setSearch(''); setStatus('all'); setAnalyst('all'); setPriorityOnly(false); setListPage(1) }
  const openQueue = (next: DossierStatus) => { navigate('dossiers'); clearFilters(); setStatus(next) }
  const table = (rows: Dossier[]) => <div className="bo-table-scroll"><table className="bo-table"><thead><tr><th scope="col">Client / dossier</th><th scope="col">Financement</th><th scope="col">Pièces</th><th scope="col">Statut</th><th scope="col">Analyste</th><th scope="col"><span className="bo-sr-only">Consulter</span></th></tr></thead><tbody>{rows.map(d => <tr key={d.id}><td><div className="bo-client-cell"><span className={`bo-avatar bo-avatar-${d.profile === 'PME' ? 'orange' : d.profile === 'TPE' ? 'purple' : 'blue'}`}>{d.initials}</span><div><button className="bo-client-link" onClick={() => openDossier(d.id)}>{d.company}</button><span>{d.id} {d.priority && <span className="bo-priority-inline">· Prioritaire</span>}</span><small>{d.city} · {dateLabel(d.date)}</small></div></div></td><td><strong>{money(d.amount)}</strong><small>{d.financing} · {d.duration} mois</small></td><td><span className="bo-doc-count"><BoIcon name="file" size={14}/>{d.documents.filter(doc => doc.status !== 'missing').length}/{d.documents.length}</span>{d.documents.some(doc => ['replace', 'missing'].includes(doc.status)) && <small className="bo-warning-text">À compléter</small>}</td><td><span className={`bo-badge bo-${STATUS[d.status].tone}`}>{STATUS[d.status].label}</span></td><td><span className="bo-analyst-cell">{analystName(d.analyst)}</span></td><td><button className="bo-icon-button" onClick={() => openDossier(d.id)} aria-label={`Ouvrir ${d.id} · ${d.company}`}><BoIcon name="arrow" size={18}/></button></td></tr>)}</tbody></table></div>

  return <div className="bo-root">
    <a className="bo-skip" href="#bo-main">Aller aux dossiers</a>
    <aside className="bo-sidebar"><a className="bo-brand" href="/backoffice"><span>w.</span><div>wafabail<small>ESPACE GESTION</small></div></a><span className="bo-sidebar-label">PILOTAGE DU FINANCEMENT</span><nav aria-label="Navigation back-office">{NAV.map(item => <button key={item.id} className={page === item.id ? 'is-active' : ''} onClick={() => navigate(item.id)} aria-current={page === item.id ? 'page' : undefined}><BoIcon name={item.icon} size={19}/>{item.label}{item.id === 'dossiers' && <span className="bo-nav-count">{dossiers.length}</span>}</button>)}</nav>
      <div className="bo-sidebar-bottom"><div className="bo-sidebar-demo"><span className="bo-demo-dot"/>Mode démonstration<p>Des exemples pour explorer le parcours, sans données réelles.</p></div><button className="bo-reset" onClick={() => setResetConfirm(!resetConfirm)}><BoIcon name="refresh" size={15}/>Réinitialiser les exemples</button><div className="bo-profile"><span className="bo-avatar">AG</span><div><strong>Amine Gestionnaire</strong><small>Compte fictif · démonstration</small></div></div></div>
    </aside>
    <div className="bo-main-wrap"><header className="bo-topbar"><div>Back-office <span>/</span> <strong>{NAV.find(item => item.id === page)?.label}</strong></div><button className="bo-icon-button bo-mobile-reset" aria-label="Réinitialiser les exemples" onClick={() => setResetConfirm(!resetConfirm)}><BoIcon name="refresh" size={16}/></button><span className="bo-avatar bo-small">AG</span></header>
      <main id="bo-main" className="bo-main" tabIndex={-1}><div className="bo-page-heading"><div><span className="bo-kicker">WAFABAIL · ESPACE DE GESTION</span><h1>{TITLES[page]}</h1><p>{SUBTITLES[page]}</p></div>{['dossiers', 'overview'].includes(page) && <button className="bo-button" onClick={exportCsv}><BoIcon name="download" size={17}/>Exporter {page === 'dossiers' ? 'la sélection' : 'les dossiers'}</button>}</div>
        {resetConfirm && <div className="bo-reset-confirm"><p>Effacer les actions de cette démo ?</p><button onClick={() => { setDossiers(createDemoDossiers()); clearFilters(); setResetConfirm(false); setToast('Exemples réinitialisés') }}>Oui, réinitialiser</button><button onClick={() => setResetConfirm(false)}>Annuler</button></div>}<div className="bo-demo-banner"><span className="bo-demo-banner-icon">ⓘ</span><p><strong>Un back-office de démonstration, interactif.</strong> Les dossiers et fichiers sont fictifs. Les actions restent dans cet onglet et sont réinitialisées au rechargement. Aucun lien avec les demandes réelles.</p></div>
        {['overview', 'dossiers'].includes(page) && <div className="bo-metrics"><button onClick={() => { navigate('dossiers'); clearFilters() }}><span>Dossiers reçus <BoIcon name="folder" size={17}/></span><strong>{dossiers.length}<small>dossiers</small></strong><small>{money(dossiers.reduce((sum, d) => sum + d.amount, 0))} de projets fictifs</small></button><button onClick={() => openQueue('new')}><span>À traiter <BoIcon name="clock" size={17}/></span><strong>{counts.new}<small>dossiers</small></strong><small><span className="bo-metric-dot bo-dot-orange"/>En attente d’affectation</small></button><button onClick={() => openQueue('analysis')}><span>En analyse <BoIcon name="users" size={17}/></span><strong>{counts.analysis}<small>dossiers</small></strong><small>Répartis dans votre équipe</small></button><button onClick={() => openQueue('revision')}><span>Retour client <BoIcon name="refresh" size={17}/></span><strong>{counts.revision}<small>dossiers</small></strong><small><span className="bo-metric-dot bo-dot-amber"/>{outstanding} pièces à compléter ou remplacer</small></button></div>}
        {page === 'overview' && <><div className="bo-overview-grid"><section className="bo-card"><div className="bo-card-heading"><h2>À regarder en priorité</h2><span className="bo-badge bo-orange">{active.filter(d => d.priority).length} dossiers</span></div>{active.filter(d => d.priority).map(d => <button className="bo-priority-item" key={d.id} onClick={() => openDossier(d.id)}><span className="bo-avatar bo-avatar-orange">{d.initials}</span><span><strong>{d.company}</strong><small>{d.project}</small></span><span className={`bo-badge bo-${STATUS[d.status].tone}`}>{STATUS[d.status].label}</span><BoIcon name="arrow" size={17}/></button>)}{!active.some(d => d.priority) && <p className="bo-muted">Aucun dossier prioritaire en cours.</p>}</section><section className="bo-card"><div className="bo-card-heading"><h2>Répartition des dossiers</h2><span className="bo-muted">{dossiers.length} au total</span></div>{Object.entries(STATUS).map(([key, item]) => <button className="bo-distribution" key={key} onClick={() => openQueue(key as DossierStatus)}><span>{item.label}</span><span className="bo-distribution-track"><span style={{width:`${counts[key as DossierStatus] / dossiers.length * 100}%`}}/></span><strong>{counts[key as DossierStatus]}</strong></button>)}</section></div><section className="bo-card bo-list-card"><div className="bo-card-heading"><h2>Dernières demandes</h2><button className="bo-text-button" onClick={() => { navigate('dossiers'); clearFilters() }}>Voir tous les dossiers <BoIcon name="arrow" size={15}/></button></div>{table(dossiers.slice().sort((a,b) => b.date.localeCompare(a.date)).slice(0,4))}</section></>}
        {page === 'dossiers' && <section className="bo-card bo-list-card"><div className="bo-status-tabs" aria-label="Filtrer par statut">{(['all', ...Object.keys(STATUS)] as const).map(key => <button key={key} className={status === key ? 'is-active' : ''} aria-pressed={status === key} onClick={() => { setStatus(key as DossierStatus | 'all'); setListPage(1) }}>{key === 'all' ? 'Tous les dossiers' : STATUS[key as DossierStatus].label}<span>{key === 'all' ? dossiers.length : counts[key as DossierStatus]}</span></button>)}</div><div className="bo-toolbar"><label className="bo-search"><BoIcon name="search" size={17}/><input aria-label="Rechercher un dossier" placeholder="Client, référence, contact ou ville…" value={search} onChange={e => { setSearch(e.target.value); setListPage(1) }}/></label><select aria-label="Filtrer par analyste" value={analyst} onChange={e => { setAnalyst(e.target.value); setListPage(1) }}><option value="all">Tous les analystes</option><option value="none">Non affectés</option>{ANALYSTS.map(a => <option value={a.id} key={a.id}>{a.name}</option>)}</select><select aria-label="Trier les dossiers" value={sort} onChange={e => setSort(e.target.value)}><option value="recent">Plus récents</option><option value="oldest">Plus anciens</option><option value="amount">Montant décroissant</option></select><button className={`bo-button ${priorityOnly ? 'bo-filter-active' : ''}`} aria-pressed={priorityOnly} onClick={() => { setPriorityOnly(!priorityOnly); setListPage(1) }}><BoIcon name="star" size={15}/>Priorité</button></div>{visible.length ? table(visible) : <div className="bo-empty"><BoIcon name="search" size={30}/><h2>Aucun dossier ne correspond</h2><p>Essayez une autre recherche ou retirez un filtre.</p><button className="bo-button" onClick={clearFilters}>Effacer les filtres</button></div>}<div className="bo-pagination"><span>{filtered.length ? `${(currentPage-1)*6+1}–${Math.min(currentPage*6,filtered.length)} sur ${filtered.length} dossiers` : '0 dossier'}</span><div><button aria-label="Page précédente" disabled={currentPage===1} onClick={() => setListPage(currentPage-1)}>←</button><span>Page {currentPage} / {pageCount}</span><button aria-label="Page suivante" disabled={currentPage===pageCount} onClick={() => setListPage(currentPage+1)}>→</button></div></div></section>}
        {page === 'documents' && <section className="bo-card bo-list-card"><div className="bo-toolbar"><label className="bo-search"><BoIcon name="search" size={17}/><input aria-label="Rechercher les documents d’un client" placeholder="Rechercher un client ou un dossier…" value={search} onChange={e => setSearch(e.target.value)}/></label><select aria-label="Filtrer les documents" value={docFilter} onChange={e => setDocFilter(e.target.value)}><option value="all">Toutes les pièces</option><option value="CIN">CIN</option><option value="Attestation ICE">ICE</option><option value="review">À vérifier</option><option value="replace">À remplacer</option><option value="missing">Manquantes</option><option value="validated">Vérifiées</option></select><span className="bo-muted">{documents.length} pièces</span></div><div className="bo-library">{documents.map(({dossier,doc}) => <button key={doc.id} className="bo-library-item" onClick={() => openDossier(dossier.id, doc.id)}><span className="bo-library-art"><BoIcon name="file" size={30}/><span>{doc.kind.startsWith('CIN') ? 'CIN' : doc.kind==='Attestation ICE' ? 'ICE' : 'PIÈCE'}</span><small>DOCUMENT FICTIF</small></span><strong>{doc.kind}</strong><span>{dossier.company}</span><small>{dossier.id}</small><span className={`bo-badge bo-${DOC_STATUS[doc.status].tone}`}>{DOC_STATUS[doc.status].label}</span></button>)}</div>{!documents.length && <div className="bo-empty"><h2>Aucune pièce correspondante</h2><p>Modifiez votre recherche ou votre filtre.</p></div>}</section>}
        {page === 'analysts' && <><div className="bo-analyst-grid">{ANALYSTS.map(a => { const assigned = dossiers.filter(d => d.analyst === a.id && ['new','analysis','revision'].includes(d.status)); return <section className="bo-card bo-analyst-card" key={a.id}><span className="bo-avatar bo-avatar-large">{a.initials}</span><h2>{a.name}</h2><p>{a.specialty}</p><span className="bo-badge bo-green">Équipe fictive</span><div className="bo-workload"><span>Charge de démonstration</span><strong>{assigned.length} / {a.capacity}</strong></div><div className="bo-distribution-track"><span style={{width:`${Math.min(assigned.length/a.capacity*100,100)}%`}}/></div><div className="bo-analyst-stats"><span><strong>{assigned.filter(d => d.status==='analysis').length}</strong>en analyse</span><span><strong>{assigned.filter(d => d.status==='revision').length}</strong>retours client</span></div><button className="bo-button" onClick={() => { navigate('dossiers'); clearFilters(); setAnalyst(a.id) }}>Consulter ses dossiers <BoIcon name="arrow" size={16}/></button></section> })}</div><div className="bo-demo-note">Les disponibilités et capacités sont des exemples d’interface, pas un planning réel.</div></>}
        {page === 'activity' && <section className="bo-card"><div className="bo-toolbar"><label className="bo-search"><BoIcon name="search" size={17}/><input aria-label="Rechercher dans l’activité" placeholder="Client, référence ou ville…" value={search} onChange={e => setSearch(e.target.value)}/></label><span className="bo-muted">{activity.length} événements</span></div><div className="bo-activity-list">{activity.map(({event,dossier}) => <article key={event.id}><span className="bo-activity-icon"><BoIcon name="clock" size={18}/></span><div><strong>{event.title}</strong><p>{event.detail}</p><button className="bo-text-button" onClick={() => openDossier(dossier.id)}>{dossier.company} · {dossier.id}</button></div><small>{dateLabel(event.date)}<span>{event.actor}</span></small></article>)}</div>{!activity.length && <div className="bo-empty"><h2>Aucun événement correspondant</h2></div>}</section>}
        <footer className="bo-footer"><span>© {new Date().getFullYear()} Wafabail · Maquette back-office</span><span><span className="bo-demo-dot"/>Aucun service de production connecté</span></footer>
      </main>
    </div>
    {selected && <DossierDrawer key={selected.id} dossier={selected} onClose={() => setSelectedId(null)} onAction={performAction} initialDocumentId={selectedDocumentId} feedback={toast}/>}
    {toast && <div className="bo-toast" role="status"><BoIcon name="check" size={18}/>{toast}<button aria-label="Fermer la notification" onClick={() => setToast('')}><BoIcon name="close" size={15}/></button></div>}
  </div>
}
